# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: gusfaleofirnando.github.io
title: HOME/AWAL
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Gusfa Leo Firnando. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook-official
    url: https://facebook.com/
  - title: gmail
    url: https://accounts.google.com/ServiceLogin?
    social:
  - title: SIF
    url: http://sif.uin-suska.ac.id/
  - title: UIN
    url: http://uin-suska.ac.id/
    
